### PR TITLE
Add accessors

### PR DESCRIPTION
**Pull request by Masa0u0**
Hello. I am a university student in Japan.
I propose the following two things

- Add accessors for Joint, Segment and RigidbodyInertia.
- Let TreeFkSolverPos_recursive and TreeJntToJacSolver hold the constant reference of the Tree.

orocos_kdl will be easier to use. Please consider.

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
I will have to check which changes are ABI compatible. As these are small changes, 8 don't want to break ABI compatibility for it.

**Comment by Masa0u0** [comment]
Thank you for your comments.
Could you tell me what I should do?

**Comment by Masa0u0** [comment]
@MatthijsBurgh 
I updated PR. Please check again.

**Comment by MatthijsBurgh** [comment]
@Masa0u0 These are the only ABI compatible changes.

**Comment by Masa0u0** [comment]
@MatthijsBurgh 
I understand.
I am disappointed that TreeFkSolverPos_recursive and TreeJntToJacSolver cannot have the const reference of Tree.

**Comment by Masa0u0** [comment]
@MatthijsBurgh 
I changed the name of the added function and added docstring to it.
I'm sorry, I made a mistake in the commit messages.

**Review by MatthijsBurgh — APPROVED** [review]

**Pull request merged**
