### PR TITLE
Fix/python3 joint none

### PR DESCRIPTION
**Pull request by smits**
A fix for the None keyword in python3 was provided in dee1e303370 but never included as it potentially broke existing working python2 scripts. This PR should properly fix it by sticking to None for python2 and only move to Fixed for python3.

ptal @vbargsten

### CODE REVIEW

**Comment by jspricke** [comment]
Hey Ruben, this just bit me when trying to port ros-kdl-parser to Python3 (in Debian). I would propose to provide the `Fixed` symbol in Python 2 as well. Is there anything else this keeps from being merged (apart from the merge conflict obviously)? Would be great to have a new release with this, so I can integrate it into the Debian package. Cheers Jochen

**Comment by luzpaz** [comment]
Any progress on this?

**Comment by meyerj** [comment]
@smits PTAL

**Comment by MatthijsBurgh** [comment]
I have included slightly difference changes of this PR in #229

**Comment by MatthijsBurgh** [comment]
This is taken care of by #229

**Pull request closed without merging**
