### PR TITLE
Added joint limits to ChainIkSolverPos_LMA

### PR DESCRIPTION
**Pull request by facontidavide**
I have added joints limit to the IK.
I don't know if this follows strictly your coding standards (by the way, sorry for the different tabulation).

We might have created a new class ChainIkSolverPos_LMA_JL, but it would have been a lot of code replicated.

### CODE REVIEW

**Comment by smits** [comment]
@facontidavide could you provide a version which is consistent with the existing API?

**Comment by rethink-forrest** [comment]
@smits The API for all existing functions and constructors is consistent. Is there a reason not to add the four new functions which are fairly straight forward?

@facontidavide, my only suggestion would be to document the four new functions. Should only take 2-3 lines each.

**Comment by rethink-forrest** [comment]
@smits Or are you asking that q_min and q_max be added to the constructor (maybe a second constructor)?  Guess it would make sense that use_joint_limits would be set to true if the limits were provided by the constructor.

**Comment by jf---** [comment]
@rethink-forrest , yes, so my comment was about that --- for instance look at the constructor of ChainIkSolverPos_NR_JL. Why would you want a different constructor / API for the exact same functionality.

**Comment by smits** [comment]
As a second thought I like the API of this solver more than the ChainIkSolverPos_NR_JL. I would propose to keep the functions for setting the limits here, add them in ChainIkSolverPos_NR_JL for consistency and add "initial" values in the constructor for ChainIkSolverPos_LMA for consistency with ChainIkSolverPos_NR_JL. This way we keep API backwards compatibility.

**Pull request closed without merging**
