### PR TITLE
Add compatibility for ROS_PYTHON_VERSION

### PR DESCRIPTION
**Pull request by tfoote**
This allows us to build it for python2 or python3 needed for noetic

https://www.ros.org/reps/rep-0149.html
Signed-off-by: Tully Foote <tfoote@osrfoundation.org>

### CODE REVIEW

**Comment by tfoote** [comment]
When this is merged the rosdistro index for noetic should be updated to use the upstream not my fork as added in https://github.com/ros/rosdistro/pull/22486: https://github.com/ros/rosdistro/pull/22486/commits/889d592643da930a213bee7afcf1865904f5db17

**Comment by meyerj** [comment]
@smits?

**Comment by tfoote** [comment]
@smits Could we merge this to get ready for noetic?

**Comment by smits** [comment]
@tfoote anything else we would need to do?

**Comment by tfoote** [comment]
@smits Thanks that's it for now. I've opened https://github.com/ros/rosdistro/pull/23487 to stop using my branch for testing.

We'll have a need for a noetic release in the not too distant future including this change. But we're still ironing out some buildfarm support issues for Buster/Focal support right now.

**Pull request merged**
