### PR TITLE
Fix OSX build

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
See https://github.com/conda-forge/orocos-kdl-feedstock/pull/1 and e.g. https://github.com/pytorch/pytorch/commit/73f6715f4725a0723d8171d3131e09ac7abf0666

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
Thanks @Tobias-Fischer, I will first try to find a way to include OSX build into travis, without doubling the number of jobs.
When travis will succeed with your commit, I will merge it.

**Comment by smits** [comment]
@MatthijsBurgh I once started trying to include OSX builds here: https://github.com/orocos/orocos_kinematics_dynamics/tree/refactor/travis-include-osx but never successfully finished it.

**Comment by Tobias-Fischer** [comment]
Friendly ping @MatthijsBurgh

**Comment by MatthijsBurgh** [comment]
I am closing this PR as it is targeted for the old SIP version of PyKDL.

**Pull request closed without merging**
